---
- hosts: control_plane
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - debug: var=join_command_raw.stdout_lines[0]


- hosts: workers
  become: yes
  become_user: root
  tasks:
    - debug: var=hostvars['control1'].join_command
    - name: Check that the node_joined exists
      stat:
        path: node_joined.txt
      register: stat_result
      #Phải remove file node_joined.txt nếu tồn tại thì đoạn code dưới mới chạy
    - name: Remove the file, if it exist already
      shell: "rm node_joined.txt"
      when: stat_result.stat.exists

    - name: join cluster
      shell: "{{ hostvars['control1'].join_command }} >> node_joined.txt"
      register: result
      #until: result.stdout.find("This node has joined the cluster:") != -1
      #retries: 3
      #delay: 20
      args:
        chdir: $HOME
        creates: node_joined.txt

